### ISSUE TITLE
Infografia Hilos 

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/infografia-de-hilos-Gregorio012#3]
[InfografiaHilos_GregorioOsorioSarmiento.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Gregorio012/files/8834057/InfografiaHilos_GregorioOsorioSarmiento.pdf)

**Comment by g00gle2401** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
